name: Validating Conventional Commits

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]


jobs:
  validate-conventional-commits:
    name: Validating Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validating PR commits
        uses: cangulo-actions/cangulo.nuke.prcommitsvalidations@v0.0.1
        with:
          validationSettingsPath: ./cicd/prCommitValidationSettings.json