name: Release New Version

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "**.tf"

jobs:
  release-new-version:
    name: Releasing new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating Release
        uses: cangulo-actions/cangulo.nuke.releasecreator@v0.0.1
        with:
          releaseSettingsPath: ./cicd/releaseSettings.json
