name: "Terraform Apply"

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "*.tf"
      - "*.tfvars"

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_PRIVATE_REPOS }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=base.tfvars
      - name: Output Terraform Variables
        run: terraform output -json > current_state_resources_info.json
      - name: Commit New Resources Report
        run: |
          git config user.name cangulo-github
          git config user.email cangulo-github@github.com
          git add .
          git commit -m "fix: updated resources report"
          git push
