name: "Terraform Apply"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release New Version"]
    branches: [main]
    types:
      - completed
    paths:
      - "**.tf"
      - "cicd/versionTracker.json"
  release:
    types: [released]


jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_PUBLIC_REPOS }}
      - name: Checkout private config repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.CONFIG_REPO}}
          token: ${{ secrets.ACCESS_PRIVATE_REPOS }}
          path: config
      - name: Update tfvars
        working-directory: config
        run: |
          new_version=$(jq '.currentVersion' ../cicd/versionTracker.json)
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          ./preparetfvars.sh $new_version
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: |
          jq -c '.[]' config/sensitive_strings.json | while read i; do
            echo "::add-mask::$i"
          done
          terraform apply -auto-approve -var-file=config/base.tfvars
      - name: Output Terraform Variables
        run: terraform output -json > config/current_state_resources_info.json
      - name: Commit New Resources Status
        working-directory: config
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name cangulo-github
            git config user.email cangulo-github@github.com
            git add .
            git commit -m "[tf-deploy]: v${{ env.NEW_VERSION }} updated tfvars files and current_state_resources_info after deployment."
            git push
          else
            echo "no changes";
          fi
